#' @title Run EBV Simulations
#' @description Run a set of scenarios and replicates to generate genotypes.
#' 
#' @param params list of parameters for scenario runs. See \code{Details} for 
#'   description of format.
#' @param num.cores number of cores to use.
#' @param fsc.exec name of fastsimcoal executable.
#' 
#' @details \code{params} must be a list with the following elements:
#' \tabular{ll}{
#'   \code{label} \tab label for the run.\cr
#'   \code{scenarios} \tab data frame of scenario specifications generated by \code{\link{makeScenarios}}.\cr
#'   \code{genetics} \tab specification of genetic data to be simulated as output from \code{\link[strataG]{fscSettingsGenetics}}.\cr
#'   \code{ploidy} \tab ploidy of genetic data.\cr
#'   \code{num.rep} \tab number of replicates to run for each scenario.\cr
#'   \code{google.drive.id} \tab id of root Google Drive to download run from.\cr
#'  }
#' 
#' @return vector of folders where scenario data and replicates were written.
#'   
#' @author Eric Archer \email{eric.archer@@noaa.gov}
#' 
#' @export
#'  
runEBVsim <- function(params, num.cores, fsc.exec = "fsc26") {
  params$folders <- writeScenarios(
    params$label, 
    params$scenarios, 
    params$google.drive.id
  )
  params$rep.id <- if(!is.null(params$folders$google)) {
    googledrive::as_id(params$folders$google) 
  } else NULL
  
  num.sc <- nrow(params$scenarios)
  params$scenario.runs <- if(num.cores == 1) {  
    lapply(1:num.sc, .runScenario, params = params, fsc.exec = fsc.exec)
  } else {
    cl <- strataG:::.setupClusters(num.cores)
    tryCatch({
      parallel::clusterEvalQ(cl, require(ebvSim))
      parallel::clusterExport(cl, c("params", "fsc.exec"), environment())
      parallel::parLapply(cl, 1:num.sc, .runScenario, params = params, fsc.exec = fsc.exec)
    }, finally = parallel::stopCluster(cl))
  }
  
  save(params, file = paste0(params$label, "_ws.rdata"))
  invisible(params)
}

#' @noRd
#' 
.runScenario <- function(sc.i, params, fsc.exec) {
  num.sc <- nrow(params$scenarios)
  sc <- params$scenarios[sc.i, ]
  cat(
    format(Sys.time()), 
    paste0(
      "---- Scenario #", sc$scenario, " (", sc.i, " / ", num.sc , ") ----\n"
    )
  )
  
  p <- runFscSim(
    label = paste0(params$label, "_sc.", sc$scenario), 
    sc = sc, 
    genetics = params$genetics,
    ploidy = params$ploidy, 
    num.rep = params$num.rep,
    use.wd = params$use.wd,
    fsc.exec = fsc.exec
  )
  
  files <- sapply(1:params$num.rep, function(sim.i) {
    gen.data <- strataG::fscReadArp(p, sim = c(1, sim.i))
    if(sc$rmetasim.ngen > 0) {
      gen.data <- gen.data %>% 
        calcFreqs() %>% 
        runRmetasim(sc = sc) %>% 
        rmetasim::landscape.make.genind() %>% 
        strataG::genind2gtypes() %>% 
        strataG::as.data.frame()
    }
    
    fname <- repFname(params$label, sc$scenario, sim.i)
    out.name <- file.path(params$folders$out, fname)
    utils::write.csv(gen.data, file = out.name, row.names = FALSE)
    if(!is.null(params$rep.id)) {
      googledrive::drive_upload(
        out.name, 
        path = params$rep.id, 
        name = fname, 
        verbose = FALSE
      )
    }
    out.name
  })
  
  if(params$delete.fsc.files) strataG::fscCleanup(p$label, p$folder)
  list(fsc.p = p, files = files)
}
